// Small, dependency-free crypto helpers for the MCP connector: HS256 JWTs
// for access tokens, HMAC-signed blobs (authorize-form state, pagination
// cursors, short-lived file links), and scrypt password hashes.

import { createHmac, createHash, randomBytes, scryptSync, timingSafeEqual } from 'crypto';

export function b64url(buf: Buffer | string): string {
  return Buffer.from(buf).toString('base64url');
}
export function fromB64url(s: string): Buffer {
  return Buffer.from(s, 'base64url');
}

export function sha256Hex(s: string): string {
  return createHash('sha256').update(s).digest('hex');
}

export function randomToken(bytes = 32): string {
  return randomBytes(bytes).toString('base64url');
}

function safeEqual(a: string, b: string): boolean {
  const x = Buffer.from(a);
  const y = Buffer.from(b);
  return x.length === y.length && timingSafeEqual(x, y);
}

// Separate keys per purpose, all derived from the one MCP_TOKEN_SECRET, so a
// value signed for one purpose (say a cursor) can never be replayed as another
// (say an access token).
function subkey(secret: string, purpose: string): Buffer {
  return createHmac('sha256', secret).update(`gb-mcp:${purpose}`).digest();
}

// ─── JWT (HS256 only) ────────────────────────────────────────────────────────

export interface AccessTokenClaims {
  iss: string;
  aud: string;
  sub: string;
  client_id: string;
  scope: string;
  iat: number;
  exp: number;
  jti: string;
  ver: string;
}

export function signJwt(claims: AccessTokenClaims, secret: string): string {
  const header = b64url(JSON.stringify({ alg: 'HS256', typ: 'at+jwt' }));
  const body = b64url(JSON.stringify(claims));
  const sig = createHmac('sha256', subkey(secret, 'access-token')).update(`${header}.${body}`).digest('base64url');
  return `${header}.${body}.${sig}`;
}

// Returns the claims only if the signature is valid and the header is exactly
// HS256 — never trusts the token's own choice of algorithm.
export function verifyJwt(token: string, secret: string): AccessTokenClaims | null {
  const parts = token.split('.');
  if (parts.length !== 3) return null;
  const [header, body, sig] = parts;
  try {
    const h = JSON.parse(fromB64url(header).toString('utf8'));
    if (h?.alg !== 'HS256') return null;
    const expected = createHmac('sha256', subkey(secret, 'access-token')).update(`${header}.${body}`).digest('base64url');
    if (!safeEqual(sig, expected)) return null;
    const claims = JSON.parse(fromB64url(body).toString('utf8'));
    return claims && typeof claims === 'object' ? claims as AccessTokenClaims : null;
  } catch {
    return null;
  }
}

// ─── Signed blobs (state, cursors, file links) ──────────────────────────────

export function signBlob(purpose: string, data: unknown, secret: string): string {
  const body = b64url(JSON.stringify(data));
  const sig = createHmac('sha256', subkey(secret, purpose)).update(body).digest('base64url');
  return `${body}.${sig}`;
}

export function verifyBlob<T>(purpose: string, blob: string, secret: string): T | null {
  const dot = blob.lastIndexOf('.');
  if (dot <= 0) return null;
  const body = blob.slice(0, dot);
  const sig = blob.slice(dot + 1);
  const expected = createHmac('sha256', subkey(secret, purpose)).update(body).digest('base64url');
  if (!safeEqual(sig, expected)) return null;
  try { return JSON.parse(fromB64url(body).toString('utf8')) as T; } catch { return null; }
}

export function hmacHex(purpose: string, value: string, secret: string): string {
  return createHmac('sha256', subkey(secret, purpose)).update(value).digest('hex');
}

// ─── Owner password (scrypt) ────────────────────────────────────────────────
// Stored in env as scrypt:N:r:p:saltB64url:hashB64url (colons, not "$": Next.js
// expands $VAR references inside .env files, which would mangle a $-format hash) — generated by
// scripts/mcp-hash-password.ts so the plaintext never lands in any file.

const SCRYPT_N = 1 << 15;
const SCRYPT_R = 8;
const SCRYPT_P = 1;
const SCRYPT_LEN = 32;

export function hashOwnerPassword(password: string): string {
  const salt = randomBytes(16);
  const hash = scryptSync(password, salt, SCRYPT_LEN, { N: SCRYPT_N, r: SCRYPT_R, p: SCRYPT_P, maxmem: 64 * 1024 * 1024 });
  return `scrypt:${SCRYPT_N}:${SCRYPT_R}:${SCRYPT_P}:${b64url(salt)}:${b64url(hash)}`;
}

export function verifyOwnerPassword(password: string, stored: string): boolean {
  const parts = stored.split(":");
  if (parts.length !== 6 || parts[0] !== 'scrypt') return false;
  const [, n, r, p, salt, hash] = parts;
  try {
    const expected = fromB64url(hash);
    const actual = scryptSync(password, fromB64url(salt), expected.length, {
      N: Number(n), r: Number(r), p: Number(p), maxmem: 64 * 1024 * 1024,
    });
    return actual.length === expected.length && timingSafeEqual(actual, expected);
  } catch {
    return false;
  }
}

// PKCE S256: BASE64URL(SHA256(verifier)) === challenge.
export function pkceS256(verifier: string): string {
  return createHash('sha256').update(verifier).digest('base64url');
}
